from flask import Flask, render_template, request, jsonify
from textblob import TextBlob
import numpy as np
import pickle 
import speech_recognition as sr
import openai
from flask_sqlalchemy import SQLAlchemy
from flask_cors import CORS
from flask import Flask, render_template, request, redirect
from flask import Flask, render_template, redirect, url_for, request
from flask_login import LoginManager, login_user, login_required, logout_user, current_user
from werkzeug.security import check_password_hash
from flask import Flask, flash, render_template, redirect, url_for
from flask import Flask, render_template, redirect, url_for
from flask_sqlalchemy import SQLAlchemy
from flask import Flask, render_template, redirect, url_for
import pickle  # For loading the ML model
 # Import your authentication blueprint
# Assuming auth is in the same directory as main.py


# Dummy data for disease prediction and precautions (For demonstration)
disease_data = {
    "fever": "Flu",
    "cough": "Common Cold",
    "headache": "Migraine",
    "fatigue": "Chronic Fatigue Syndrome",
    "shortness of breath": "Asthma",
    "nausea": "Gastroenteritis",
    "vomiting": "Food Poisoning",
    "joint pain": "Rheumatoid Arthritis",
    "chest pain": "Heart Disease",
    "dizziness": "Vertigo",
    "blurred vision": "Diabetic Retinopathy",
    "sore throat": "Tonsillitis",
    "runny nose": "Sinusitis",
    "loss of appetite": "Hepatitis",
    "swollen lymph nodes": "Lymphoma",
    "rash": "Psoriasis",
    "bloody stool": "Colorectal Cancer",
    "abdominal pain": "Irritable Bowel Syndrome",
    "weight loss": "Hyperthyroidism",
    "frequent urination": "Diabetes",
    "muscle weakness": "Myasthenia Gravis",
    "chills": "Malaria",
    "persistent cough": "Tuberculosis",
    "sweating": "Hyperhidrosis",
    "sore muscles": "Fibromyalgia",
    "memory loss": "Alzheimer's Disease",
    "numbness": "Multiple Sclerosis",
    "back pain": "Herniated Disc",
    "blisters": "Shingles",
    "swollen ankles": "Chronic Kidney Disease",
    "ear pain": "Otitis Media",
    "painful urination": "Urinary Tract Infection",
    "skin lesions": "Leprosy",
    "yellowing skin": "Jaundice",
    "blood in urine": "Kidney Stones",
    "dry mouth": "Sjögren's Syndrome",
    "night sweats": "Tuberculosis",
    "stomach cramps": "Peptic Ulcer Disease",
    "itchy skin": "Eczema",
    "bloody cough": "Lung Cancer",
    "persistent headache": "Cluster Headache",
    "heart palpitations": "Atrial Fibrillation",
    "itchy eyes": "Allergic Conjunctivitis",
    "stiff neck": "Meningitis",
    "dark urine": "Liver Disease",
    "cold hands": "Raynaud's Disease",
    "ringing in ears": "Tinnitus",
    "frequent headaches": "Tension Headache",
    "numbness in legs": "Diabetic Neuropathy",
    "pelvic pain": "Endometriosis",
    "leg swelling": "Deep Vein Thrombosis",
    "blurry vision": "Glaucoma",
    "chronic cough": "COPD",
    "dry skin": "Hypothyroidism",
    "difficulty swallowing": "Achalasia",
    "frequent thirst": "Diabetes Insipidus",
    "excessive thirst": "Diabetes Mellitus",
    "cramps": "Dehydration",
    "abnormal bleeding": "Hemophilia",
    "pale skin": "Anemia",
    "severe sweating": "Hyperhidrosis",
    "hoarseness": "Laryngitis",
    "abnormal bruising": "Vitamin K Deficiency",
    "liver pain": "Cirrhosis",
    "itchy scalp": "Seborrheic Dermatitis",
    "painful joints": "Gout",
    "difficulty breathing": "Pneumonia",
    "red eyes": "Conjunctivitis",
    "painful swallowing": "Pharyngitis",
    "shaking hands": "Parkinson's Disease",
    "hair loss": "Alopecia",
    "coughing up blood": "Bronchitis",
    "chronic fatigue": "Chronic Fatigue Syndrome",
    "difficulty concentrating": "ADHD",
    "sensitivity to light": "Migraine",
    "extreme fatigue": "Hypothyroidism",
    "persistent diarrhea": "Crohn's Disease",
    "swollen face": "Angioedema",
    "blurry vision": "Macular Degeneration",
    "painful sores": "Cold Sores",
    "swollen abdomen": "Ascites",
    "nausea and vomiting": "Gallstones",
    "high blood pressure": "Hypertension",
    "severe headache": "Migraine",
    "unexplained weight loss": "Cancer",
    "dry eyes": "Sjögren's Syndrome",
    "heartburn": "Gastroesophageal Reflux Disease",
    "bloody stools": "Colitis",
    "chronic pain": "Fibromyalgia",
    "frequent urination": "Bladder Infection",
    "painful abdomen": "Appendicitis",
    "bruising easily": "Leukemia",
    "burning sensation in chest": "GERD",
    "intense pain in legs": "Peripheral Artery Disease",
    "vomiting blood": "Esophageal Varices",
    "fatigue and weakness": "Anemia",
    "swollen joints": "Rheumatoid Arthritis",
    "numbness in hands": "Carpal Tunnel Syndrome",
    "indigestion": "Peptic Ulcer",
    "lump in breast": "Breast Cancer",
    "feeling faint": "Low Blood Pressure",
    "excessive hunger": "Hyperthyroidism",
    "bleeding gums": "Gingivitis",
    "tightness in chest": "Asthma",
    "red rash": "Chickenpox",
    "persistent thirst": "Diabetes",
    "difficulty walking": "Parkinson's Disease",
    "painful urination": "Urinary Tract Infection",
    "tiredness": "Anemia",
    "wheezing": "Asthma",
    "loss of balance": "Vestibular Disorder",
    "red spots on skin": "Rash",
    "stiffness in muscles": "Myositis",
    "painful skin": "Shingles",
    "chronic pain": "Arthritis",
    "chronic sore throat": "Chronic Laryngitis",
    "blackouts": "Seizures",
    "lightheadedness": "Low Blood Sugar",
    "blue skin": "Cyanosis",
    "feeling cold": "Hypothyroidism",
    "red eyes": "Pink Eye",
    "itchy rash": "Allergic Reaction",
    "persistent fever": "Typhoid",
    "coughing up mucus": "Bronchitis",
    "swelling in legs": "Heart Failure",
    "painful mouth sores": "Canker Sores",
    "depression": "Major Depressive Disorder",
    "nausea and dizziness": "Labyrinthitis",
    "irregular heartbeat": "Atrial Fibrillation",
    "high cholesterol": "Hyperlipidemia",
    "sweating excessively": "Hyperhidrosis",
    "lack of coordination": "Ataxia",
    "itchy eyes": "Allergic Conjunctivitis",
    "painful feet": "Plantar Fasciitis",
    "swollen lymph nodes": "Mononucleosis",
    "sore joints": "Osteoarthritis",
    "muscle cramps": "Electrolyte Imbalance",
    "feeling faint": "Hypotension",
    "itchy throat": "Allergy",
    "headache and nausea": "Migraine",
    "joint swelling": "Gout",
    "feeling anxious": "Anxiety Disorder",
    "pain behind eyes": "Sinus Headache",
    "heart irregularities": "Arrhythmia",
    "unexplained bruising": "Vitamin C Deficiency",
    "sore mouth": "Oral Thrush",
    "sweaty palms": "Hyperhidrosis",
    "painful back": "Scoliosis",
    "high body temperature": "Fever",
    "chronic nasal congestion": "Allergic Rhinitis",
    "pain in ribs": "Rib Fracture",
    "slow healing wounds": "Diabetes",
    "confusion": "Delirium",
    "numb fingers": "Raynaud's Disease",
    "chronic bloating": "Irritable Bowel Syndrome",
    "white patches in mouth": "Leukoplakia",
    "mouth ulcers": "Aphthous Stomatitis",
    "painful stomach": "Gastritis",
    "head shaking": "Tremors",
    "abdominal bloating": "Celiac Disease",
    "lower back pain": "Sciatica",
    "increased thirst": "Diabetes",
    "wheezing and coughing": "Asthma",
    "painful rash": "Shingles",
    "hunger and fatigue": "Diabetes",
    "tiredness and dizziness": "Anemia",
    "pain in the chest": "Angina",
    "blurred vision": "Cataracts",
    "cramps and bloating": "Premenstrual Syndrome",
    "rashes and blisters": "Chickenpox",
    "heart disease": "Coronary Artery Disease",
    "severe neck pain": "Cervical Spondylosis",
    "sore eyes": "Conjunctivitis",
    "skin discoloration": "Vitiligo",
    "muscle spasms": "Charley Horse",
    "swollen feet": "Heart Failure",
    "increased urination": "Kidney Disease",
    "eye pain": "Uveitis",
    "persistent cough with mucus": "Bronchitis",
    "painful neck": "Cervical Radiculopathy",
    "painful joints": "Osteoarthritis",
    "painful throat": "Laryngitis",
    "fainting": "Syncope",
    "shaky hands": "Essential Tremor",
    "painful shoulder": "Rotator Cuff Injury",
    "constant hunger": "Hyperglycemia",
    "swollen legs": "Lymphedema",
    "chronic leg pain": "Restless Leg Syndrome",
    "red skin": "Erythema",
    "black stools": "Gastrointestinal Bleeding",
    "cough": "Common Cold",
    "headache": "Migraine",
    "fatigue": "Chronic Fatigue Syndrome",
    "shortness of breath": "Asthma",
    "nausea": "Gastroenteritis",
    "vomiting": "Food Poisoning",
    "joint pain": "Rheumatoid Arthritis",
    "chest pain": "Heart Disease",
    "dizziness": "Vertigo",
    "blurred vision": "Diabetic Retinopathy",
    "sore throat": "Tonsillitis",
    "runny nose": "Sinusitis",
    "loss of appetite": "Hepatitis",
    "swollen lymph nodes": "Lymphoma",
    "rash": "Psoriasis",
    "bloody stool": "Colorectal Cancer",
    "abdominal pain": "Irritable Bowel Syndrome",
    "weight loss": "Hyperthyroidism",
    "frequent urination": "Diabetes",
    "muscle weakness": "Myasthenia Gravis",
    "chills": "Malaria",
    "persistent cough": "Tuberculosis",
    "sweating": "Hyperhidrosis",
    "sore muscles": "Fibromyalgia",
    "memory loss": "Alzheimer's Disease",
    "numbness": "Multiple Sclerosis",
    "back pain": "Herniated Disc",
    "blisters": "Shingles",
    "swollen ankles": "Chronic Kidney Disease",
    "ear pain": "Otitis Media",
    "painful urination": "Urinary Tract Infection",
    "skin lesions": "Leprosy",
    "yellowing skin": "Jaundice",
    "blood in urine": "Kidney Stones",
    "dry mouth": "Sjögren's Syndrome",
    "night sweats": "Tuberculosis",
    "stomach cramps": "Peptic Ulcer Disease",
    "itchy skin": "Eczema",
    "bloody cough": "Lung Cancer",
    "persistent headache": "Cluster Headache",
    "heart palpitations": "Atrial Fibrillation",
    "itchy eyes": "Allergic Conjunctivitis",
    "stiff neck": "Meningitis",
    "dark urine": "Liver Disease",
    "cold hands": "Raynaud's Disease",
    "ringing in ears": "Tinnitus",
    "frequent headaches": "Tension Headache",
    "numbness in legs": "Diabetic Neuropathy",
    "pelvic pain": "Endometriosis",
    "leg swelling": "Deep Vein Thrombosis",
    "blurry vision": "Glaucoma",
    "chronic cough": "COPD",
    "dry skin": "Hypothyroidism",
    "difficulty swallowing": "Achalasia",
    "frequent thirst": "Diabetes Insipidus",
    "excessive thirst": "Diabetes Mellitus",
    "cramps": "Dehydration",
    "abnormal bleeding": "Hemophilia",
    "pale skin": "Anemia",
    "severe sweating": "Hyperhidrosis",
    "hoarseness": "Laryngitis",
    "abnormal bruising": "Vitamin K Deficiency",
    "liver pain": "Cirrhosis",
    "itchy scalp": "Seborrheic Dermatitis",
    "painful joints": "Gout",
    "difficulty breathing": "Pneumonia",
    "red eyes": "Conjunctivitis",
    "painful swallowing": "Pharyngitis",
    "shaking hands": "Parkinson's Disease",
    "hair loss": "Alopecia",
    "coughing up blood": "Bronchitis",
    "chronic fatigue": "Chronic Fatigue Syndrome",
    "difficulty concentrating": "ADHD",
    "sensitivity to light": "Migraine",
    "extreme fatigue": "Hypothyroidism",
    "persistent diarrhea": "Crohn's Disease",
    "swollen face": "Angioedema",
    "blurry vision": "Macular Degeneration",
    "painful sores": "Cold Sores",
    "swollen abdomen": "Ascites",
    "nausea and vomiting": "Gallstones",
    "high blood pressure": "Hypertension",
    "severe headache": "Migraine",
    "unexplained weight loss": "Cancer",
    "dry eyes": "Sjögren's Syndrome",
    "heartburn": "Gastroesophageal Reflux Disease",
    "bloody stools": "Colitis",
    "chronic pain": "Fibromyalgia",
    "frequent urination": "Bladder Infection",
    "painful abdomen": "Appendicitis",
    "bruising easily": "Leukemia",
    "burning sensation in chest": "GERD",
    "intense pain in legs": "Peripheral Artery Disease",
    "vomiting blood": "Esophageal Varices",
    "fatigue and weakness": "Anemia",
    "swollen joints": "Rheumatoid Arthritis",
    "numbness in hands": "Carpal Tunnel Syndrome",
    "indigestion": "Peptic Ulcer",
    "lump in breast": "Breast Cancer",
    "feeling faint": "Low Blood Pressure",
    "excessive hunger": "Hyperthyroidism",
    "bleeding gums": "Gingivitis",
    "tightness in chest": "Asthma",
    "red rash": "Chickenpox",
    "persistent thirst": "Diabetes",
    "difficulty walking": "Parkinson's Disease",
    "painful urination": "Urinary Tract Infection",
    "tiredness": "Anemia",
    "wheezing": "Asthma",
    "loss of balance": "Vestibular Disorder",
    "red spots on skin": "Rash",
    "stiffness in muscles": "Myositis",
    "painful skin": "Shingles",
    "chronic pain": "Arthritis",
    "chronic sore throat": "Chronic Laryngitis",
    "blackouts": "Seizures",
    "lightheadedness": "Low Blood Sugar",
    "blue skin": "Cyanosis",
    "feeling cold": "Hypothyroidism",
    "red eyes": "Pink Eye",
    "itchy rash": "Allergic Reaction",
    "persistent fever": "Typhoid",
    "coughing up mucus": "Bronchitis",
    "swelling in legs": "Heart Failure",
    "painful mouth sores": "Canker Sores",
    "depression": "Major Depressive Disorder",
    "nausea and dizziness": "Labyrinthitis",
    "irregular heartbeat": "Atrial Fibrillation",
    "high cholesterol": "Hyperlipidemia",
    "sweating excessively": "Hyperhidrosis",
    "lack of coordination": "Ataxia",
    "itchy eyes": "Allergic Conjunctivitis",
    "painful feet": "Plantar Fasciitis",
    "swollen lymph nodes": "Mononucleosis",
    "sore joints": "Osteoarthritis",
    "muscle cramps": "Electrolyte Imbalance",
    "feeling faint": "Hypotension",
    "itchy throat": "Allergy",
    "headache and nausea": "Migraine",
    "joint swelling": "Gout",
    "feeling anxious": "Anxiety Disorder",
    "pain behind eyes": "Sinus Headache",
    "heart irregularities": "Arrhythmia",
    "unexplained bruising": "Vitamin C Deficiency",
    "sore mouth": "Oral Thrush",
    "sweaty palms": "Hyperhidrosis",
    "painful back": "Scoliosis",
    "high body temperature": "Fever",
    "chronic nasal congestion": "Allergic Rhinitis",
    "pain in ribs": "Rib Fracture",
    "slow healing wounds": "Diabetes",
    "confusion": "Delirium",
    "numb fingers": "Raynaud's Disease",
    "chronic bloating": "Irritable Bowel Syndrome",
    "white patches in mouth": "Leukoplakia",
    "mouth ulcers": "Aphthous Stomatitis",
    "painful stomach": "Gastritis",
    "head shaking": "Tremors",
    "abdominal bloating": "Celiac Disease",
    "lower back pain": "Sciatica",
    "increased thirst": "Diabetes",
    "wheezing and coughing": "Asthma",
    "painful rash": "Shingles",
    "hunger and fatigue": "Diabetes",
    "tiredness and dizziness": "Anemia",
    "pain in the chest": "Angina",
    "blurred vision": "Cataracts",
    "cramps and bloating": "Premenstrual Syndrome",
    "rashes and blisters": "Chickenpox",
    "heart disease": "Coronary Artery Disease",
    "severe neck pain": "Cervical Spondylosis",
    "sore eyes": "Conjunctivitis",
    "skin discoloration": "Vitiligo",
    "muscle spasms": "Charley Horse",
    "swollen feet": "Heart Failure",
    "increased urination": "Kidney Disease",
    "eye pain": "Uveitis",
    "persistent cough with mucus": "Bronchitis",
    "painful neck": "Cervical Radiculopathy",
    "painful joints": "Osteoarthritis",
    "painful throat": "Laryngitis",
    "fainting": "Syncope",
    "shaky hands": "Essential Tremor",
    

 }

precautions_data = {
    "flu": ["Rest", "Drink plenty of fluids", "Avoid close contact with others"],
    "common cold": ["Stay hydrated", "Get plenty of sleep", "Use a humidifier"],
    "migraine": ["Rest in a dark room", "Stay hydrated", "Avoid bright lights"],
    "chronic fatigue syndrome": ["Get enough rest", "Exercise moderately", "Avoid stress"],
    "asthma": ["Avoid triggers", "Use inhalers as prescribed", "Keep airways clear"],
    "gastroenteritis": ["Stay hydrated", "Avoid dairy products", "Eat light foods"],
    "food poisoning": ["Hydrate well", "Avoid greasy foods", "Eat small, frequent meals"],
    "rheumatoid arthritis": ["Stay active", "Avoid stress", "Use joint protection techniques"],
    "heart disease": ["Exercise regularly", "Maintain a healthy diet", "Avoid smoking and alcohol"],
    "vertigo": ["Rest in a comfortable position", "Avoid sudden head movements", "Stay hydrated"],
    "diabetic retinopathy": ["Monitor blood sugar", "Regular eye check-ups", "Protect eyes from bright light"],
    "tonsillitis": ["Rest", "Gargle warm salt water", "Stay hydrated"],
    "sinusitis": ["Use a humidifier", "Stay hydrated", "Apply warm compress to the face"],
    "hepatitis": ["Avoid alcohol", "Eat a healthy diet", "Avoid unprotected sex"],
    "lymphoma": ["Follow prescribed treatments", "Maintain a healthy diet", "Stay active"],
    "psoriasis": ["Use moisturizers", "Avoid triggers", "Apply prescribed medications"],
    "colorectal cancer": ["Eat a high-fiber diet", "Exercise regularly", "Get regular screenings"],
    "irritable bowel syndrome": ["Avoid trigger foods", "Manage stress", "Eat smaller meals"],
    "hyperthyroidism": ["Take thyroid medication", "Monitor thyroid levels", "Avoid excessive iodine"],
    "diabetes": ["Monitor blood sugar", "Maintain a healthy diet", "Exercise regularly"],
    "myasthenia gravis": ["Avoid stress", "Take prescribed medications", "Get enough rest"],
    "malaria": ["Use mosquito repellent", "Sleep under a mosquito net", "Take anti-malarial medications"],
    "tuberculosis": ["Complete prescribed medication course", "Cover mouth when coughing", "Avoid crowded places"],
    "hyperhidrosis": ["Wear breathable clothing", "Use antiperspirants", "Stay hydrated"],
    "fibromyalgia": ["Exercise regularly", "Manage stress", "Get enough rest"],
    "alzheimer's disease": ["Engage in cognitive exercises", "Stay socially active", "Eat a brain-healthy diet"],
    "multiple sclerosis": ["Follow prescribed medications", "Exercise regularly", "Avoid overheating"],
    "herniated disc": ["Rest", "Avoid heavy lifting", "Use proper posture when sitting and standing"],
    "shingles": ["Take antiviral medications", "Use cool compresses", "Avoid scratching the rash"],
    "chronic kidney disease": ["Control blood pressure", "Limit salt intake", "Stay hydrated"],
    "otitis media": ["Keep ears dry", "Avoid inserting objects in ears", "Take prescribed antibiotics"],
    "urinary tract infection": ["Drink plenty of water", "Urinate frequently", "Wipe front to back"],
    "leprosy": ["Take prescribed antibiotics", "Avoid close contact with infected individuals", "Maintain good hygiene"],
    "jaundice": ["Avoid alcohol", "Follow a liver-friendly diet", "Stay hydrated"],
    "kidney stones": ["Increase water intake", "Avoid excessive salt", "Eat a balanced diet"],
    "sjögren's syndrome": ["Use eye drops", "Stay hydrated", "Avoid smoking"],
    "tuberculosis": ["Complete medication course", "Stay away from others during contagious phase", "Wear a mask in crowded places"],
    "peptic ulcer disease": ["Avoid spicy foods", "Take prescribed antacids", "Eat smaller, more frequent meals"],
    "eczema": ["Apply moisturizer", "Avoid triggers", "Use prescribed topical creams"],
    "lung cancer": ["Avoid smoking", "Get regular screenings", "Follow prescribed treatment plan"],
    "cluster headache": ["Avoid alcohol", "Practice relaxation techniques", "Consider preventive medications"],
    "atrial fibrillation": ["Take prescribed medications", "Limit alcohol intake", "Monitor heart rate"],
    "allergic conjunctivitis": ["Avoid allergens", "Use antihistamine eye drops", "Wear sunglasses outdoors"],
    "meningitis": ["Complete prescribed antibiotic course", "Avoid close contact with others", "Rest in a quiet, dark room"],
    "liver disease": ["Avoid alcohol", "Follow a healthy liver diet", "Monitor liver function regularly"],
    "raynaud's disease": ["Keep extremities warm", "Manage stress", "Avoid smoking"],
    "tinnitus": ["Use white noise machines", "Avoid loud sounds", "Manage stress"],
    "tension headache": ["Practice relaxation techniques", "Avoid triggers", "Use pain relievers as prescribed"],
    "diabetic neuropathy": ["Monitor blood sugar", "Take prescribed medications", "Exercise regularly"],
    "endometriosis": ["Manage pain with medications", "Consider hormonal therapies", "Exercise regularly"],
    "deep vein thrombosis": ["Move regularly", "Avoid sitting for long periods", "Wear compression stockings"],
    "glaucoma": ["Use prescribed eye drops", "Get regular eye exams", "Avoid heavy lifting"],
    "copd": ["Avoid smoking", "Use prescribed inhalers", "Exercise regularly"],
    "hypothyroidism": ["Take thyroid medication", "Eat a balanced diet", "Exercise regularly"],
    "achalasia": ["Eat smaller meals", "Avoid lying down after eating", "Consider medications or surgery"],
    "diabetes insipidus": ["Drink plenty of water", "Take prescribed medications", "Monitor fluid intake"],
    "diabetes mellitus": ["Monitor blood sugar levels", "Eat a balanced diet", "Exercise regularly"],
    "dehydration": ["Increase fluid intake", "Avoid caffeine and alcohol", "Eat foods with high water content"],
    "hemophilia": ["Avoid trauma", "Take prescribed clotting factor", "Avoid certain medications"],
    "anemia": ["Eat iron-rich foods", "Take prescribed iron supplements", "Avoid excessive caffeine"],
    "hyperhidrosis": ["Use prescription antiperspirants", "Consider Botox injections", "Wear breathable clothing"],
    "laryngitis": ["Rest your voice", "Stay hydrated", "Avoid throat irritants"],
    "vitamin k deficiency": ["Eat foods rich in vitamin K", "Take prescribed supplements", "Avoid anticoagulants"],
    "cirrhosis": ["Avoid alcohol", "Follow a liver-friendly diet", "Take prescribed medications"],
    "seborrheic dermatitis": ["Use gentle shampoos", "Apply prescribed creams", "Avoid harsh hair products"],
    "gout": ["Avoid purine-rich foods", "Stay hydrated", "Take prescribed medications"],
    "pneumonia": ["Take antibiotics as prescribed", "Rest", "Drink plenty of fluids"],
    "pink eye": ["Avoid touching eyes", "Wash hands regularly", "Use prescribed eye drops"],
    "pharyngitis": ["Gargle with warm salt water", "Drink warm fluids", "Take pain relievers as prescribed"],
    "parkinson's disease": ["Exercise regularly", "Take prescribed medications", "Stay socially active"],
    "alopecia": ["Consider topical treatments", "Consult a dermatologist", "Manage stress"],
    "bronchitis": ["Rest", "Drink fluids", "Avoid smoking"],
    "chronic fatigue syndrome": ["Rest regularly", "Manage stress", "Exercise as tolerated"],
    "adhd": ["Establish a routine", "Limit distractions", "Consider medications"],
    "migraine": ["Avoid triggers", "Use prescribed medications", "Get enough rest"],
    "hypothyroidism": ["Take thyroid medication", "Monitor thyroid levels", "Eat a balanced diet"],
    "crohn's disease": ["Avoid trigger foods", "Take prescribed medications", "Manage stress"],
    "angioedema": ["Take antihistamines", "Avoid known triggers", "Consult a doctor for treatment"],
    "macular degeneration": ["Eat a diet rich in antioxidants", "Get regular eye exams", "Wear sunglasses"],
    "cold sores": ["Avoid touching sores", "Use antiviral creams", "Stay hydrated"],
    "ascites": ["Limit salt intake", "Take prescribed diuretics", "Monitor weight"],
    "gallstones": ["Avoid fatty foods", "Drink plenty of fluids", "Consult a doctor for possible surgery"],
    "hypertension": ["Exercise regularly", "Reduce salt intake", "Take prescribed medications"],
    "cluster headache": ["Avoid triggers", "Take prescribed medications", "Use relaxation techniques"],
    "vitamin c deficiency": ["Increase vitamin C intake", "Take prescribed supplements", "Eat fruits and vegetables"],
    "oral thrush": ["Use prescribed antifungal medications", "Maintain good oral hygiene", "Avoid smoking"],
    "scoliosis": ["Monitor spinal health", "Consider physical therapy", "Avoid heavy lifting"],
    "cancer": ["Follow prescribed treatment plan", "Maintain a healthy diet", "Stay active"],
    "delirium": ["Ensure a calm environment", "Stay hydrated", "Take prescribed medications"],
    "raynaud's disease": ["Keep extremities warm", "Avoid stress", "Quit smoking"],
    "celiac disease": ["Avoid gluten-containing foods", "Read food labels carefully", "Consult a nutritionist"],
    "sciatica": ["Exercise regularly", "Use proper posture", "Consider physical therapy"],
    "diabetes": ["Monitor blood sugar", "Exercise regularly", "Eat a balanced diet"],
    "asthma": ["Avoid triggers", "Use inhalers", "Stay hydrated"],
    "shingles": ["Take prescribed antiviral medications", "Rest", "Avoid scratching the rash"],
    "fibromyalgia": ["Exercise regularly", "Manage stress", "Get enough rest"],
    "gout": ["Avoid purine-rich foods", "Take prescribed medications", "Stay hydrated"]
}



medications_data = {
    "flu": ["Acetaminophen", "Ibuprofen", "Oseltamivir", "Zanamivir"],
    "common cold": ["Cough syrup", "Decongestants", "Antihistamines", "Paracetamol"],
    "migraine": ["Pain relievers", "Triptans", "Aspirin", "Sumatriptan"],
    "chronic fatigue syndrome": ["Modafinil", "Antidepressants", "Pain relievers"],
    "asthma": ["Albuterol", "Fluticasone", "Salbutamol", "Montelukast"],
    "gastroenteritis": ["Oral rehydration salts", "Antidiarrheal medications", "Antiemetics"],
    "food poisoning": ["Oral rehydration salts", "Antibiotics (if bacterial)", "Anti-nausea medication"],
    "rheumatoid arthritis": ["Methotrexate", "Hydroxychloroquine", "NSAIDs", "Biologics (e.g., Humira)"],
    "heart disease": ["Aspirin", "Beta-blockers", "ACE inhibitors", "Statins"],
    "vertigo": ["Antihistamines", "Meclizine", "Diazepam", "Betahistine"],
    "diabetic retinopathy": ["Laser treatment", "Anti-VEGF injections", "Steroid injections"],
    "tonsillitis": ["Antibiotics (e.g., Penicillin)", "Pain relievers", "Saltwater gargles"],
    "sinusitis": ["Nasal corticosteroids", "Saline nasal spray", "Decongestants", "Antibiotics (if bacterial)"],
    "hepatitis": ["Antiviral medications", "Interferon", "Liver transplant (if severe)"],
    "lymphoma": ["Chemotherapy", "Radiation therapy", "Immunotherapy"],
    "psoriasis": ["Topical corticosteroids", "Calcipotriene", "Biologics (e.g., Etanercept)"],
    "colorectal cancer": ["Chemotherapy", "Radiation therapy", "Surgery", "Targeted therapy"],
    "irritable bowel syndrome": ["Antispasmodics", "Laxatives", "Antidiarrheal medications", "Fiber supplements"],
    "hyperthyroidism": ["Methimazole", "Propylthiouracil", "Radioactive iodine"],
    "diabetes": ["Metformin", "Insulin", "Sulfonylureas", "GLP-1 agonists"],
    "myasthenia gravis": ["Acetylcholinesterase inhibitors", "Thymectomy", "Immunosuppressive drugs"],
    "malaria": ["Chloroquine", "Artemisinin-based combination therapies (ACTs)", "Mefloquine"],
    "tuberculosis": ["Isoniazid", "Rifampicin", "Pyrazinamide", "Ethambutol"],
    "hyperhidrosis": ["Antiperspirants", "Botox injections", "Iontophoresis", "Medications (e.g., oxybutynin)"],
    "fibromyalgia": ["Antidepressants", "Pain relievers", "Pregabalin", "Duloxetine"],
    "alzheimer's disease": ["Donepezil", "Rivastigmine", "Galantamine", "Memantine"],
    "multiple sclerosis": ["Beta interferons", "Glatiramer acetate", "Steroids", "Fingolimod"],
    "herniated disc": ["Pain relievers", "Steroid injections", "Surgical options (if severe)"],
    "shingles": ["Acyclovir", "Valacyclovir", "Famciclovir", "Pain relievers"],
    "chronic kidney disease": ["ACE inhibitors", "Angiotensin II receptor blockers (ARBs)", "Erythropoiesis-stimulating agents"],
    "otitis media": ["Antibiotics (e.g., Amoxicillin)", "Pain relievers", "Warm compress"],
    "urinary tract infection": ["Antibiotics (e.g., Nitrofurantoin)", "Pain relievers (e.g., Phenazopyridine)"],
    "leprosy": ["Rifampicin", "Clofazimine", "Dapsone"],
    "jaundice": ["Treatment depends on the underlying cause (e.g., antiviral medications, pain relievers)"],
    "kidney stones": ["Pain relievers", "Alpha-blockers", "Lithotripsy", "Surgery (if necessary)"],
    "sjögren's syndrome": ["Artificial tears", "Hydroxychloroquine", "Immunosuppressive medications"],
    "tuberculosis": ["Isoniazid", "Rifampicin", "Pyrazinamide", "Ethambutol"],
    "peptic ulcer disease": ["Proton pump inhibitors", "H2 blockers", "Antibiotics (for H. pylori infection)"],
    "eczema": ["Topical corticosteroids", "Moisturizers", "Antihistamines"],
    "lung cancer": ["Chemotherapy", "Radiation therapy", "Targeted therapy", "Immunotherapy"],
    "cluster headache": ["Triptans", "Oxygen therapy", "Verapamil", "Steroids"],
    "atrial fibrillation": ["Anticoagulants", "Beta-blockers", "Calcium channel blockers", "Ablation therapy"],
    "allergic conjunctivitis": ["Antihistamine eye drops", "Steroid eye drops", "Oral antihistamines"],
    "meningitis": ["Antibiotics (e.g., Ceftriaxone)", "Steroids", "Vaccination (for prevention)"],
    "liver disease": ["Antiviral medications", "Liver transplant", "Diuretics", "Nutritional supplements"],
    "raynaud's disease": ["Calcium channel blockers", "Vasodilators", "Nitrates"],
    "tinnitus": ["Antidepressants", "Antianxiety medications", "Cognitive behavioral therapy"],
    "tension headache": ["Pain relievers (e.g., Ibuprofen)", "Relaxation techniques", "Physical therapy"],
    "diabetic neuropathy": ["Antidepressants", "Anticonvulsants", "Pain relievers"],
    "endometriosis": ["Nonsteroidal anti-inflammatory drugs (NSAIDs)", "Hormonal therapy", "Surgery (in severe cases)"],
    "deep vein thrombosis": ["Anticoagulants", "Compression stockings", "Thrombolytics"],
    "glaucoma": ["Beta-blockers (e.g., Timolol)", "Prostaglandin analogs (e.g., Latanoprost)", "Laser surgery"],
    "copd": ["Bronchodilators", "Steroids", "Oxygen therapy", "Pulmonary rehabilitation"],
    "hypothyroidism": ["Levothyroxine", "Liothyronine"],
    "achalasia": ["Botox injections", "Calcium channel blockers", "Surgery (e.g., Heller myotomy)"],
    "diabetes insipidus": ["Desmopressin", "Diuretics", "Thiazide diuretics"],
    "diabetes mellitus": ["Insulin", "Metformin", "Sulfonylureas", "GLP-1 agonists"],
    "dehydration": ["Oral rehydration salts", "Intravenous fluids", "Electrolyte solutions"],
    "hemophilia": ["Factor VIII", "Factor IX", "Desmopressin"],
    "anemia": ["Iron supplements", "Vitamin B12 supplements", "Folic acid"],
    "hyperhidrosis": ["Botox injections", "Medications (e.g., oxybutynin)", "Iontophoresis"],
    "laryngitis": ["Corticosteroids", "Pain relievers", "Voice rest"],
    "vitamin k deficiency": ["Vitamin K supplements", "Blood clotting factor replacement"],
    "cirrhosis": ["Antiviral medications", "Liver transplant", "Diuretics"],
    "seborrheic dermatitis": ["Topical corticosteroids", "Ketoconazole", "Topical antifungals"],
    "gout": ["Allopurinol", "Colchicine", "Nonsteroidal anti-inflammatory drugs (NSAIDs)"],
    "pneumonia": ["Antibiotics", "Antiviral medications", "Pain relievers"],
    "pink eye": ["Antibiotic eye drops", "Artificial tears", "Antihistamine eye drops"],
    "pharyngitis": ["Antibiotics (for bacterial infections)", "Pain relievers", "Saltwater gargles"],
    "parkinson's disease": ["Levodopa", "Dopamine agonists", "MAO-B inhibitors"],
    "alopecia": ["Minoxidil", "Finasteride", "Corticosteroids"],
    "bronchitis": ["Bronchodilators", "Cough suppressants", "Antibiotics (if bacterial)"],
    "chronic fatigue syndrome": ["Antidepressants", "Pain relievers", "Cognitive behavioral therapy"],
    "adhd": ["Stimulants (e.g., Methylphenidate)", "Non-stimulants (e.g., Atomoxetine)", "Behavioral therapy"],
    "migraine": ["Triptans", "Pain relievers (e.g., Ibuprofen)", "Antiemetics"],
    "hypothyroidism": ["Levothyroxine", "Liothyronine", "Thyroid hormone replacement therapy"],
    "crohn's disease": ["Immunosuppressants", "Steroids", "Biologics"],
    "angioedema": ["Antihistamines", "Corticosteroids", "Epinephrine"],
    "macular degeneration": ["Anti-VEGF injections", "Laser therapy", "Antioxidant vitamins"],
    "cold sores": ["Acyclovir", "Valacyclovir", "Famciclovir"],
    "ascites": ["Diuretics", "Paracentesis", "Albumin infusion"],
    "gallstones": ["Pain relievers", "Ursodeoxycholic acid", "Cholecystectomy (surgery)"],
    "hypertension": ["ACE inhibitors", "Beta-blockers", "Diuretics", "Calcium channel blockers"],
    "cluster headache": ["Oxygen therapy", "Triptans", "Verapamil", "Steroids"],
    "vitamin c deficiency": ["Vitamin C supplements", "Citrus fruits", "Vegetables (e.g., bell peppers)"],
    "oral thrush": ["Antifungal medications (e.g., Nystatin)", "Oral antifungals (e.g., Fluconazole)", "Good oral hygiene"],
    "scoliosis": ["Physical therapy", "Bracing", "Surgery (in severe cases)"],
    "cancer": ["Chemotherapy", "Radiation therapy", "Targeted therapy", "Immunotherapy"],
    "delirium": ["Antipsychotics", "Benzodiazepines", "Cognitive stimulation therapy"],
    "raynaud's disease": ["Calcium channel blockers", "Vasodilators", "Nitrates"],
    "celiac disease": ["Gluten-free diet", "Nutritional supplements", "Anti-inflammatory medications"],
    "sciatica": ["Pain relievers", "Physical therapy", "Steroid injections"],
    "diabetes": ["Insulin", "Metformin", "Sulfonylureas", "GLP-1 agonists"],
    "asthma": ["Albuterol", "Fluticasone", "Montelukast", "Salbutamol"],
    "shingles": ["Acyclovir", "Valacyclovir", "Pain relievers", "Steroids"],
    "fibromyalgia": ["Pregabalin", "Duloxetine", "Pain relievers", "Antidepressants"],
    "gout": ["Allopurinol", "Colchicine", "NSAIDs", "Steroids"]
}



workouts_data = {
    "flu": ["Light walking", "Stretching exercises", "Yoga", "Breathing exercises"],
    "common cold": ["Gentle yoga", "Breathing exercises", "Stretching", "Short walks"],
    "migraine": ["Rest", "Neck stretches", "Breathing exercises", "Gentle yoga"],
    "chronic fatigue syndrome": ["Gentle walking", "Tai chi", "Stretching", "Yoga"],
    "asthma": ["Breathing exercises", "Swimming", "Walking", "Cycling"],
    "gastroenteritis": ["Rest", "Hydration exercises", "Gentle walking"],
    "food poisoning": ["Light walking", "Gentle stretching", "Hydration exercises"],
    "rheumatoid arthritis": ["Low-impact walking", "Stretching", "Water aerobics", "Yoga"],
    "heart disease": ["Walking", "Cycling", "Swimming", "Light resistance training"],
    "vertigo": ["Balance exercises", "Gentle walking", "Tai chi", "Stretching exercises"],
    "diabetic retinopathy": ["Gentle walking", "Tai chi", "Yoga", "Stretching exercises"],
    "tonsillitis": ["Rest", "Gentle stretching", "Breathing exercises"],
    "sinusitis": ["Breathing exercises", "Gentle walking", "Yoga"],
    "hepatitis": ["Gentle walking", "Stretching exercises", "Low-intensity yoga"],
    "lymphoma": ["Gentle walking", "Stretching", "Low-intensity swimming"],
    "psoriasis": ["Gentle yoga", "Stretching exercises", "Walking", "Breathing exercises"],
    "colorectal cancer": ["Walking", "Cycling", "Yoga", "Stretching exercises"],
    "irritable bowel syndrome": ["Gentle walking", "Yoga", "Stretching", "Breathing exercises"],
    "hyperthyroidism": ["Yoga", "Gentle walking", "Breathing exercises", "Tai chi"],
    "diabetes": ["Walking", "Cycling", "Swimming", "Yoga"],
    "myasthenia gravis": ["Gentle walking", "Tai chi", "Stretching exercises", "Yoga"],
    "malaria": ["Rest", "Gentle walking", "Stretching exercises"],
    "tuberculosis": ["Gentle walking", "Stretching", "Breathing exercises"],
    "hyperhidrosis": ["Breathing exercises", "Yoga", "Light walking"],
    "fibromyalgia": ["Gentle walking", "Yoga", "Stretching exercises", "Swimming"],
    "alzheimer's disease": ["Gentle walking", "Swimming", "Stretching", "Cognitive exercises"],
    "multiple sclerosis": ["Stretching exercises", "Yoga", "Water aerobics", "Gentle walking"],
    "herniated disc": ["Gentle walking", "Stretching exercises", "Low-impact swimming"],
    "shingles": ["Gentle walking", "Stretching exercises", "Rest", "Breathing exercises"],
    "chronic kidney disease": ["Walking", "Cycling", "Swimming", "Yoga"],
    "otitis media": ["Rest", "Gentle stretching", "Breathing exercises"],
    "urinary tract infection": ["Gentle walking", "Breathing exercises", "Stretching exercises"],
    "leprosy": ["Gentle walking", "Stretching exercises", "Yoga"],
    "jaundice": ["Light walking", "Breathing exercises", "Yoga"],
    "kidney stones": ["Walking", "Stretching exercises", "Breathing exercises"],
    "sjögren's syndrome": ["Gentle walking", "Stretching exercises", "Tai chi"],
    "tuberculosis": ["Gentle walking", "Breathing exercises", "Stretching exercises"],
    "peptic ulcer disease": ["Gentle walking", "Stretching exercises", "Breathing exercises"],
    "eczema": ["Gentle walking", "Yoga", "Stretching exercises"],
    "lung cancer": ["Gentle walking", "Stretching exercises", "Breathing exercises"],
    "cluster headache": ["Rest", "Breathing exercises", "Neck stretches"],
    "atrial fibrillation": ["Gentle walking", "Yoga", "Breathing exercises", "Tai chi"],
    "allergic conjunctivitis": ["Rest", "Breathing exercises", "Yoga"],
    "meningitis": ["Rest", "Breathing exercises", "Stretching exercises"],
    "liver disease": ["Walking", "Stretching exercises", "Yoga"],
    "raynaud's disease": ["Gentle walking", "Yoga", "Stretching exercises"],
    "tinnitus": ["Gentle walking", "Breathing exercises", "Yoga"],
    "tension headache": ["Gentle walking", "Stretching exercises", "Breathing exercises"],
    "diabetic neuropathy": ["Walking", "Stretching exercises", "Tai chi"],
    "endometriosis": ["Gentle walking", "Yoga", "Breathing exercises"],
    "deep vein thrombosis": ["Walking", "Stretching", "Elevating legs"],
    "glaucoma": ["Gentle walking", "Yoga", "Stretching exercises"],
    "copd": ["Walking", "Cycling", "Swimming", "Breathing exercises"],
    "hypothyroidism": ["Yoga", "Gentle walking", "Stretching exercises", "Tai chi"],
    "achalasia": ["Gentle walking", "Breathing exercises", "Stretching exercises"],
    "diabetes insipidus": ["Walking", "Stretching", "Breathing exercises"],
    "diabetes mellitus": ["Walking", "Cycling", "Swimming", "Yoga"],
    "dehydration": ["Hydration exercises", "Gentle walking", "Stretching exercises"],
    "hemophilia": ["Stretching exercises", "Gentle walking", "Swimming (low impact)"],
    "anemia": ["Gentle walking", "Stretching exercises", "Yoga"],
    "hyperhidrosis": ["Breathing exercises", "Light walking", "Yoga"],
    "laryngitis": ["Rest", "Breathing exercises", "Gentle stretching"],
    "vitamin k deficiency": ["Light walking", "Gentle stretching", "Breathing exercises"],
    "cirrhosis": ["Gentle walking", "Stretching exercises", "Breathing exercises"],
    "seborrheic dermatitis": ["Gentle walking", "Stretching exercises", "Yoga"],
    "gout": ["Gentle walking", "Stretching exercises", "Water aerobics"],
    "pneumonia": ["Breathing exercises", "Gentle walking", "Stretching exercises"],
    "pink eye": ["Rest", "Breathing exercises", "Gentle stretching"],
    "pharyngitis": ["Rest", "Breathing exercises", "Gentle walking"],
    "parkinson's disease": ["Walking", "Tai chi", "Stretching exercises", "Yoga"],
    "alopecia": ["Gentle walking", "Stretching exercises", "Yoga"],
    "bronchitis": ["Breathing exercises", "Gentle walking", "Coughing exercises"],
    "chronic fatigue syndrome": ["Gentle walking", "Yoga", "Tai chi", "Stretching exercises"],
    "adhd": ["Walking", "Cycling", "Yoga", "Breathing exercises"],
    "migraine": ["Gentle walking", "Neck stretches", "Rest", "Yoga"],
    "hypothyroidism": ["Yoga", "Gentle walking", "Stretching exercises", "Tai chi"],
    "crohn's disease": ["Walking", "Yoga", "Gentle swimming", "Stretching exercises"],
    "angioedema": ["Rest", "Breathing exercises", "Gentle walking"],
    "macular degeneration": ["Gentle walking", "Tai chi", "Stretching exercises"],
    "cold sores": ["Rest", "Gentle walking", "Breathing exercises"],
    "ascites": ["Gentle walking", "Breathing exercises", "Stretching exercises"],
    "gallstones": ["Gentle walking", "Stretching exercises", "Breathing exercises"],
    "hypertension": ["Walking", "Cycling", "Yoga", "Stretching exercises"],
    "cluster headache": ["Rest", "Breathing exercises", "Neck stretches"],
    "vitamin c deficiency": ["Walking", "Stretching exercises", "Breathing exercises"],
    "oral thrush": ["Gentle walking", "Breathing exercises", "Yoga"],
    "scoliosis": ["Stretching exercises", "Yoga", "Swimming"],
    "cancer": ["Gentle walking", "Stretching exercises", "Breathing exercises", "Yoga"],
    "delirium": ["Rest", "Cognitive exercises", "Gentle walking"],
    "raynaud's disease": ["Gentle walking", "Stretching exercises", "Yoga"],
    "celiac disease": ["Gentle walking", "Stretching exercises", "Yoga"],
    "sciatica": ["Gentle walking", "Stretching exercises", "Yoga"],
    "diabetes": ["Walking", "Cycling", "Swimming", "Yoga"],
    "asthma": ["Breathing exercises", "Swimming", "Walking", "Cycling"],
    "shingles": ["Gentle walking", "Stretching exercises", "Rest", "Breathing exercises"],
    "fibromyalgia": ["Gentle walking", "Yoga", "Stretching exercises", "Swimming"],
    "gout": ["Allopurinol", "Colchicine", "NSAIDs", "Steroids"]
}

diets_data = {
    "flu": ["Chicken soup", "Ginger tea", "Lemon and honey", "Garlic", "Turmeric milk"],
    "common cold": ["Citrus fruits", "Garlic", "Hot tea", "Honey", "Ginger"],
    "migraine": ["Low-carb foods", "Magnesium-rich foods", "Dark leafy greens", "Almonds"],
    "chronic fatigue syndrome": ["High-protein diet", "Leafy greens", "Omega-3-rich foods"],
    "asthma": ["Ginger", "Turmeric", "Omega-3 fatty acids", "Honey"],
    "gastroenteritis": ["Bananas", "Rice", "Applesauce", "Toast (BRAT diet)"],
    "food poisoning": ["Electrolyte drinks", "Clear broth", "Bananas", "Plain rice"],
    "rheumatoid arthritis": ["Omega-3 fatty acids", "Turmeric", "Leafy greens"],
    "heart disease": ["Oatmeal", "Avocados", "Olive oil", "Nuts", "Salmon"],
    "vertigo": ["Hydrating foods", "Ginger", "Leafy greens", "Vitamin D-rich foods"],
    "diabetic retinopathy": ["Leafy greens", "Berries", "Omega-3-rich foods"],
    "tonsillitis": ["Warm broths", "Soft foods", "Honey", "Ginger tea"],
    "sinusitis": ["Pineapple", "Garlic", "Cayenne pepper", "Vitamin C-rich foods"],
    "hepatitis": ["Leafy greens", "Berries", "Lean protein", "Turmeric"],
    "lymphoma": ["High-protein diet", "Leafy greens", "Fruits", "Probiotic foods"],
    "psoriasis": ["Omega-3 fatty acids", "Avocados", "Turmeric", "Berries"],
    "colorectal cancer": ["Fiber-rich foods", "Whole grains", "Leafy greens", "Beans"],
    "irritable bowel syndrome": ["Low-FODMAP foods", "Bananas", "Oats", "Rice"],
    "hyperthyroidism": ["Cruciferous vegetables", "Berries", "Nuts", "Dairy"],
    "diabetes": ["Whole grains", "Leafy greens", "Nuts", "Lean protein"],
    "myasthenia gravis": ["Soft foods", "Lean protein", "Omega-3-rich foods"],
    "malaria": ["Leafy greens", "Citrus fruits", "Ginger", "Probiotics"],
    "tuberculosis": ["High-protein diet", "Leafy greens", "Eggs", "Milk"],
    "hyperhidrosis": ["Sage tea", "Magnesium-rich foods", "Coconut water"],
    "fibromyalgia": ["Omega-3-rich foods", "Leafy greens", "Berries", "Turmeric"],
    "alzheimer's disease": ["Leafy greens", "Berries", "Nuts", "Whole grains"],
    "multiple sclerosis": ["Anti-inflammatory foods", "Leafy greens", "Salmon"],
    "herniated disc": ["Calcium-rich foods", "Omega-3-rich foods", "Leafy greens"],
    "shingles": ["Vitamin B12-rich foods", "Leafy greens", "Yogurt"],
    "chronic kidney disease": ["Low-sodium diet", "Lean protein", "Leafy greens"],
    "otitis media": ["Vitamin C-rich foods", "Ginger", "Probiotics"],
    "urinary tract infection": ["Cranberry juice", "Yogurt", "Garlic", "Water"],
    "leprosy": ["Vitamin C-rich foods", "Garlic", "Leafy greens"],
    "jaundice": ["Leafy greens", "Turmeric", "Carrots", "Papaya"],
    "kidney stones": ["Citrus fruits", "Watermelon", "Low-oxalate foods"],
    "sjögren's syndrome": ["Omega-3-rich foods", "Coconut water", "Leafy greens"],
    "peptic ulcer disease": ["Bananas", "Probiotics", "Ginger", "Oats"],
    "eczema": ["Omega-3-rich foods", "Turmeric", "Berries", "Leafy greens"],
    "lung cancer": ["Leafy greens", "Turmeric", "Berries", "Cruciferous vegetables"],
    "cluster headache": ["Magnesium-rich foods", "Almonds", "Leafy greens"],
    "atrial fibrillation": ["Potassium-rich foods", "Leafy greens", "Nuts"],
    "allergic conjunctivitis": ["Vitamin C-rich foods", "Turmeric", "Garlic"],
    "meningitis": ["Protein-rich foods", "Leafy greens", "Vitamin C-rich foods"],
    "liver disease": ["Leafy greens", "Beets", "Turmeric", "Carrots"],
    "raynaud's disease": ["Magnesium-rich foods", "Omega-3 fatty acids"],
    "tinnitus": ["Magnesium-rich foods", "Leafy greens", "Bananas"],
    "tension headache": ["Magnesium-rich foods", "Leafy greens", "Nuts"],
    "diabetic neuropathy": ["Omega-3-rich foods", "Leafy greens", "Turmeric"],
    "endometriosis": ["Omega-3-rich foods", "Leafy greens", "Turmeric"],
    "deep vein thrombosis": ["Omega-3-rich foods", "Garlic", "Ginger"],
    "glaucoma": ["Leafy greens", "Carrots", "Omega-3 fatty acids"],
    "copd": ["Leafy greens", "Omega-3-rich foods", "Citrus fruits"],
    "hypothyroidism": ["Iodine-rich foods", "Selenium-rich foods", "Leafy greens"],
    "achalasia": ["Soft foods", "Smoothies", "Soups"],
    "dehydration": ["Coconut water", "Electrolytes", "Watermelon"],
    "hemophilia": ["Leafy greens", "Citrus fruits", "Vitamin K-rich foods"],
    "anemia": ["Iron-rich foods", "Leafy greens", "Beets"],
    "laryngitis": ["Honey", "Ginger tea", "Warm broths"],
    "cirrhosis": ["Leafy greens", "Beets", "Carrots"],
    "seborrheic dermatitis": ["Omega-3-rich foods", "Leafy greens", "Avocados"],
    "gout": ["Cherries", "Low-purine foods", "Leafy greens"],
    "pneumonia": ["Leafy greens", "Ginger", "Turmeric"],
    "pink eye": ["Vitamin A-rich foods", "Carrots", "Turmeric"],
    "pharyngitis": ["Honey", "Ginger tea", "Warm broths"],
    "parkinson's disease": ["Leafy greens", "Berries", "Nuts"],
    "alopecia": ["Protein-rich foods", "Omega-3 fatty acids", "Leafy greens"],
    "bronchitis": ["Ginger", "Turmeric", "Leafy greens"],
    "adhd": ["High-protein foods", "Omega-3-rich foods", "Leafy greens"],
    "crohn's disease": ["Low-FODMAP foods", "Bananas", "Rice"],
    "angioedema": ["Low-histamine foods", "Leafy greens"],
    "macular degeneration": ["Leafy greens", "Carrots", "Omega-3-rich foods"],
    "cold sores": ["Lysine-rich foods", "Leafy greens"],
    "hypertension": ["Leafy greens", "Bananas", "Nuts"],
    "celiac disease": ["Gluten-free grains", "Leafy greens"],
    "sciatica": ["Anti-inflammatory foods", "Leafy greens"],
    "vitamin c deficiency": ["Citrus fruits", "Berries"],
    "oral thrush": ["Probiotic foods", "Garlic", "Coconut oil"],
    "scoliosis": ["Calcium-rich foods", "Leafy greens"],
    "raynaud's disease": ["Magnesium-rich foods", "Leafy greens"]
}
app = Flask(__name__)




# Load the trained ML model (the file should be saved as 'model.pkl')
svc = pickle.load(open('svc.pkl','rb'))
 #User Modelapp.config.from_object(Config)

# Initialize the extensions with the Flask app

@app.route('/')
def home():
    return render_template('index.html')

@app.route('/predict', methods=['POST'])
def predict():
    # Get data from the form
    name = request.form['name']
    age = request.form['age']
    location = request.form['location']
    symptoms = request.form['symptoms']

    # Predict disease based on symptoms (Basic approach for demo)
    symptoms_list = symptoms.lower().split(",")  # Split symptoms
    predicted_disease = "Unknown Disease"
    
    for symptom in symptoms_list:
        if symptom in disease_data:
            predicted_disease = disease_data[symptom]
            break
    
    # Fetch the related data
    if predicted_disease != "Unknown Disease":
        dis_des = "This is a brief description of " + predicted_disease
        my_precautions = precautions_data.get(predicted_disease.lower(), [])
        medications = medications_data.get(predicted_disease.lower(), [])
        workout = workouts_data.get(predicted_disease.lower(), [])
        my_diet = diets_data.get(predicted_disease.lower(), [])
    else:
        dis_des = "No description available"
        my_precautions = []
        medications = []
        workout = []
        my_diet = []

    # Render the result page with predictions
    return render_template(
        'index.html', 
        name=name,
        age=age,
        location=location,
        symptoms=symptoms,
        predicted_disease=predicted_disease,
        dis_des=dis_des,
        my_precautions=my_precautions,
        medications=medications,
        workout=workout,
        my_diet=my_diet
    )
# about view funtion and path
@app.route('/about')
def about():
    return render_template("about.html")
# contact view funtion and path
@app.route('/contact')
def contact():
    return render_template("contact.html")

# developer view funtion and path
@app.route('/developer')
def developer():
    return render_template("developer.html")

# about view funtion and path
@app.route('/blog')
def blog():
    return render_template("blog.html")


if __name__ == '__main__':
    app.run(debug=True)
